development:
  adapter: postgresql
  database: multiblog_development
  pool: 5
  timeout: 5000
  username: er3
  password: password1

test:
  adapter: postgresql
  database: multiblog_test
  pool: 5
  timeout: 5000
  username: er3
  password: password1

production:
  adapter: postgresql
  database: multiblog_production
  pool: 5
  timeout: 5000
  username: er3_postgres
  password: 1Password!